### ISSUE TITLE
DB Schema Load in postgres docker instance

### ISSUE THREAD

**Issue by nagkumar** [sqlcomponents/sqlcomponents#27]
Need to create movies db in docker postgres instance.. else the error we get while runnign this test is

G:\DWork\opensource\jug\sc\sqlcomponents\core\src\test\java\org\sqlcomponents\core\crawler\CrawlerTest.java
-------------------------------------------------------------------------------
Test set: org.sqlcomponents.core.crawler.CrawlerTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.51 s <<< FAILURE! - in org.sqlcomponents.core.crawler.CrawlerTest
getDatabase  Time elapsed: 0.501 s  <<< ERROR!
java.lang.NullPointerException
	at org.sqlcomponents.core.crawler.CrawlerTest.getDatabase(CrawlerTest.java:35)

**Comment by nagkumar** [comment]
Fixed the code to assert for this value not to be null.

-------------------------------------------------------------------------------
Test set: org.sqlcomponents.core.crawler.CrawlerTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.448 s <<< FAILURE! - in org.sqlcomponents.core.crawler.CrawlerTest
getDatabase  Time elapsed: 0.432 s  <<< FAILURE!
java.lang.AssertionError: TableType can't be null for 'PARTITIONED INDEX', Check if all tables are created in Database
	at org.sqlcomponents.core.crawler.CrawlerTest.getDatabase(CrawlerTest.java:35)

**Comment by nagkumar** [comment]
![image](https://user-images.githubusercontent.com/332234/159167399-65bd24c9-a81a-46a9-9119-d96419ff96e3.png)

Upgrade from 
42.2.18 --> 42.3.3
fails with above error

**Comment by nagkumar** [comment]
With 42.2.18

![image](https://user-images.githubusercontent.com/332234/159167552-6c6f9c12-339a-4649-80d6-43e01960b4fd.png)

With 42.3.3

![image](https://user-images.githubusercontent.com/332234/159167603-53d22fb0-1090-4622-93b9-c06c274a9ca4.png)

**Comment by Hari-Nikesh-R** [comment]
Implemented: `TableType` enum now includes `PARTITIONED_INDEX` and all other metadata types to prevent NPEs during crawling.
