### ISSUE TITLE
Min JDK needed is JDK 11, on JDK 8 it fails due to invalid --illegal-access=permit jvm option

### ISSUE THREAD

**Issue by nagkumar** [sqlcomponents/sqlcomponents#39]
On JDK 8, the core fails and also in in JDK 17 #17

```
java -version
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)
```

![image](https://user-images.githubusercontent.com/332234/174527010-43d3acb2-15c2-4e61-a6d9-b3d4677b540d.png)

the error is

![image](https://user-images.githubusercontent.com/332234/174527132-c729eaa0-d22f-4599-9faa-efa39250e74c.png)

sqlcomponents\core\target\surefire-reports\2022-06-20T10-29-07_242.dumpstream

````
# Created at 2022-06-20T10:16:21.909
Unrecognized option: --illegal-access=permit
```

exact error it gives is

G:\DWork\osource\jug\sc\sqlcomponents\core>mvn clean package
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------------< org.sqlcomponents:core >-----------------------
[INFO] Building Core 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ core ---
[INFO] Deleting G:\DWork\osource\jug\sc\sqlcomponents\core\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory G:\DWork\osource\jug\sc\sqlcomponents\core\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 31 source files to G:\DWork\osource\jug\sc\sqlcomponents\core\target\classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory G:\DWork\osource\jug\sc\sqlcomponents\core\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to G:\DWork\osource\jug\sc\sqlcomponents\core\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.22.0:test (default-test) @ core ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.018 s
[INFO] Finished at: 2022-06-20T10:24:05+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project core: There are test failures.
[ERROR]
[ERROR] Please refer to G:\DWork\osource\jug\sc\sqlcomponents\core\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C "d:\Apps\Dev\langs\java\jdk\8.x\321\jre\bin\java --illegal-access=permit -jar C:\Users\RAJANA~1\AppData\Local\Temp\surefire972451428007190915\surefirebooter8680357189448517041.jar "C:\Users\Raja Nagendra Kumar\AppData\Local\Temp\surefire972451428007190915" 2022-06-20T10-24-05_047-jvmRun1 surefire3054959387883976916tmp surefire_01798455188600539551tmp"
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was cmd.exe /X /C "d:\Apps\Dev\langs\java\jdk\8.x\321\jre\bin\java --illegal-access=permit -jar C:\Users\RAJANA~1\AppData\Local\Temp\surefire972451428007190915\surefirebooter8680357189448517041.jar "C:\Users\Raja Nagendra Kumar\AppData\Local\Temp\surefire972451428007190915" 2022-06-20T10-24-05_047-jvmRun1 surefire3054959387883976916tmp surefire_01798455188600539551tmp"
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:671)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1194)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1022)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:868)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:301)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:211)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:165)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:157)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:121)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:127)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR]

**Comment by nagkumar** [comment]
On JDK 17, option is removed

# Created at 2022-06-20T10:35:06.699
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option --illegal-access=permit; support was removed in 17.0

![image](https://user-images.githubusercontent.com/332234/174528982-f8a387fd-2815-4445-ac9c-038a2012bc46.png)

why is --illegal-access this option needed...

**Comment by nagkumar** [comment]
#18

**Comment by sathishk** [comment]
Minimum JDK  supported is 11
